### ISSUE TITLE
Script not detecting latest version

### ISSUE THREAD

**Issue by christopherpm** [TomChantler/Update-Plex#2]
Hi, I have my Plexpass token in the script, and I have beta set to true.

As of today (17th May 2023), the script is showing the I have 1.32.1.6999-91e1e2e2c installed, and that the latest version is also 1.32.1.6999-91e1e2e2c.

However, Plex server is showing me that 1.32.2.7002 is available for download. Sure enough, if I go to https://www.plex.tv/media-server-downloads/ and choose the Linux distro, the current version for download is 1.32.2.7002-86cfcc10c

Why isn't the script detecting this?

**Comment by christopherpm** [comment]
Never mind. I figured it out. The downloaded script had the line:-

plex_token=$PUTYOURSHERE

I put my token after the $ sign. Once I removed the $ sign, it all worked ok.

**Comment by TomChantler** [comment]
Thanks for letting me know that you fixed it. I'll close this now.

**Comment by TomChantler** [comment]
I have changed the part of the download script which said
```
plex_token=$PUTYOURSHERE
```
and removed the `$`, so it is now the same as the blog article.
```
plex_token=PUTYOURSHERE
```

**Comment by thenamelessthing** [comment]
Sorry to reopen this topic. But I have the same situation and my token is properly set...

![image](https://github.com/TomChantler/Update-Plex/assets/10235448/8f349d3c-a27e-4863-97a7-33c760965763)


But on plex a newer version (1.32.5.7210) is available...

![image](https://github.com/TomChantler/Update-Plex/assets/10235448/1ef2ace9-aa1a-4e33-bb7b-5278b307b18c)

**Comment by TomChantler** [comment]
Is this still not working? I tried it just now and it seems to be working. 

First, I grabbed my token, as described at this point in my article: https://tomssl.com/update-plex-server-on-ubuntu-automatically/#a-note-about-the-beta-plexpass-channel.

Then I downloaded the latest script and inserted my token. Like this (I used nano to edit the file).

```
tom@tc-plex:~$ curl -sLOJ toms.sl/update-plex.sh
tom@tc-plex:~$ chmod +x update-plex.sh 
tom@tc-plex:~$ nano update-plex.sh 
tom@tc-plex:~$ sudo ./update-plex.sh -bn
Beta Channel = true
Dry Run = true
Force Download = false
Overwrite File = false
Architecture = amd64
Latest version:    1.32.5.7210-77f7f99fa
Installed version: 1.32.4.7195-7c8f9d3b6
------------------------------------------------------------
Need to upgrade...
Found latest version at https://downloads.plex.tv/plex-media-server-new/1.32.5.7210-77f7f99fa/debian/plexmediaserver_1.32.5.7210-77f7f99fa_amd64.deb
Downloading plexmediaserver_1.32.5.7210-77f7f99fa_amd64.deb...
Done
```

As you can see, I used Dry Run mode (`-n` flag), so that it didn't actually run the update, because somebody was watching something when I ran the test.

**Comment by thenamelessthing** [comment]
Hi, thanks. Re-doing the steps, I think I didn't download the latest version of the script (I had forgotten to do sudo) and as the folder where I had placed the script was in /opt it never downloaded the latest version.

Now it works!
